AdminUser.create!([
  {email: "admin@yahoo.com", encrypted_password: "$2a$11$6ojVSRL4wdMVYaTOpSN77uqViXuj43wQ2Q2.8De2Shvpdl43TBNdO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 14, current_sign_in_at: "2016-10-30 00:37:28", last_sign_in_at: "2016-10-29 02:47:57", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"}
])
Movie.create!([
  {title: "The Amazing Spider-Man", year: 2012, checked_out: false, reserved: false, description: "After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to solve the mystery of his parent's mysterious death.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMjMyOTM4MDMxNV5BMl5BanBnXkFtZTcwNjIyNzExOA@@._V1_SX300.jpg", rated: "PG-13", runtime: "136 min", actors: "Andrew Garfield, Emma Stone, Rhys Ifans, Denis Leary", imdb_rating: "7.0"},
  {title: "300", year: 2006, checked_out: false, reserved: false, description: "King Leonidas of Sparta and a force of 300 men fight the Persians at Thermopylae in 480 B.C.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMjAzNTkzNjcxNl5BMl5BanBnXkFtZTYwNDA4NjE3._V1_SX300.jpg", rated: "R", runtime: "117 min", actors: "Gerard Butler, Lena Headey, Dominic West, David Wenham", imdb_rating: "7.7"},
  {title: "300: Rise of an Empire", year: 2014, checked_out: false, reserved: false, description: "After its victory over Leonidas' 300, the Persian Army under the command of Xerxes marches towards the major Greek city-states. The Democratic city of Athens, first on the path of Xerxes' army, bases its strength on its fleet, led by admiral Themistocles. Themistocles is forced to an unwilling alliance with the traditional rival of Athens, oligarchic Sparta whose might lies with its superior infantry troops. But Xerxes still reigns supreme in numbers over sea and land.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTEwNTU2MjAwMDdeQTJeQWpwZ15BbWU3MDk2Njc2Njk@._V1_SX300.jpg", rated: "R", runtime: "102 min", actors: "Sullivan Stapleton, Eva Green, Lena Headey, Hans Matheson", imdb_rating: "6.2"},
  {title: "3:10 to Yuma", year: 2007, checked_out: false, reserved: false, description: "Rancher Dan Evans heads into Bisbee to clear up issues concerning the sale of his land when he witnesses the closing events of a stagecoach robbery led by famed outlaw Ben Wade. Shortly thereafter, Wade is captured by the law in Bisbee and Evans finds himself one of the escorts who will take Wade to the 3:10 to Yuma train in Contention for the reward of $200. Evans's effort to take Wade to the station is in part an effort to save his land but also part of an inner battle to determine whether he can be more than just a naive rancher in the eyes of his impetuous and gunslinging son William Evans. The transport to Contention is hazardous and filled with ambushes by Indians, pursuits by Wade's vengeful gang and Wade's own conniving and surreptitious demeanor that makes the ride all the more intense.", times_rented: nil, img_url: "https://image.tmdb.org/t/p/original/9Nwkh0eQmkymEOR0ovAALtjSIZW.jpg", rated: "R", runtime: "122 min", actors: "Russell Crowe, Christian Bale, Logan Lerman, Dallas Roberts", imdb_rating: "7.7"},
  {title: "47 Ronin", year: 2013, checked_out: false, reserved: false, description: "While hunting in the forest, Lord Asano of Ako and his samurai find a young half-breed and take him with them to live in the castle. Several years later, Lord Asano holds a tournament to welcome the Shogun to Ako. The night after the tournament, Lord Asano is bewitched into hurting Lord Kira of Nagato, and is punished into committing seppuku by the Shogun. Realizing that it was a Lord Kira's evil plot, the samurais and the half-breed sets out for revenge against the Shogun's order.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTc0MjE2NzE0OV5BMl5BanBnXkFtZTgwNTU5MjE1MDE@._V1_SX300.jpg", rated: "PG-13", runtime: "128", actors: "Keanu Reeves, Hiroyuki Sanada, Ko Shibasaki, Tadanobu Asano", imdb_rating: "6.3"},
  {title: "50/50", year: 2011, checked_out: false, reserved: false, description: "Adam is a 27 year old writer of radio programs and is diagnosed with a rare form of spinal cancer. With the help of his best friend, his mother, and a young therapist at the cancer center, Adam learns what and who the most important things in his life are.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BNjg3ODQyNTIyN15BMl5BanBnXkFtZTcwMjUzNzM5NQ@@._V1_SX300.jpg", rated: "R", runtime: "100 min", actors: "Joseph Gordon-Levitt, Seth Rogen, Anna Kendrick, Bryce Dallas Howard", imdb_rating: "7.7"},
  {title: "9", year: 2009, checked_out: false, reserved: false, description: "In a world destroyed in a war between man and machine, a hand-stitched doll with the number 9 written on its back comes to life. The world he has awakened in is frightening, but he quickly learns that he is not alone and that there are others like him, also with a single digit written on their back. The first one he encounters is 2 who tells him something of what happened to the world. 2 is also thrilled with the disk 9 is carrying, one with three unique symbols on the front. 9 soon learns that the disk and some of the other dolls who are prepared to die for the good of humankind may be the last hope for man's salvation.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTY2ODE1MTgxMV5BMl5BanBnXkFtZTcwNTM1NTM2Mg@@._V1_SX300.jpg", rated: "PG-13", runtime: "79 min", actors: "Christopher Plummer, Martin Landau, John C. Reilly, Crispin Glover", imdb_rating: "7.1"},
  {title: "Aloha", year: 2015, checked_out: false, reserved: false, description: "A celebrated military contractor returns to the site of his greatest career triumphs - the US Space program in Honolulu, Hawaii - and reconnects with a long-ago love while unexpectedly falling for the hard-charging Air Force watchdog assigned to him.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTg4Mjc0NTE1NV5BMl5BanBnXkFtZTgwNzcwNTQ3NTE@._V1_SX300.jpg", rated: "PG-13", runtime: "105 min", actors: "Bradley Cooper, Emma Stone, Rachel McAdams, Bill Murray", imdb_rating: "5.4"},
  {title: "The Amazing Spider-Man 2", year: 2014, checked_out: false, reserved: false, description: "When New York is put under siege by Oscorp, it is up to Spider-Man to save the city he swore to protect as well as his loved ones.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BOTA5NDYxNTg0OV5BMl5BanBnXkFtZTgwODE5NzU1MTE@._V1_SX300.jpg", rated: "PG-13", runtime: "142 min", actors: "Andrew Garfield, Emma Stone, Jamie Foxx, Dane DeHaan", imdb_rating: "6.7"},
  {title: "13 Hours", year: 2016, checked_out: false, reserved: true, description: "During an attack on a U.S. compound in Libya, a security team struggles to make sense out of the chaos.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMjU3OTQ5NDc3Ml5BMl5BanBnXkFtZTgwOTEwNTkxNzE@._V1_SX300.jpg", rated: "R", runtime: "144 min", actors: "John Krasinski, James Badge Dale, Pablo Schreiber, David Denman", imdb_rating: "7.3"},
  {title: "22 Jump Street", year: 2014, checked_out: false, reserved: true, description: "After making their way through high school (twice), big changes are in store for officers Schmidt (Jonah Hill) and Jenko (Channing Tatum) when they go deep undercover at a local college. But when Jenko meets a kindred spirit on the football team, and Schmidt infiltrates the bohemian art major scene, they begin to question their partnership. Now they don't have to just crack the case - they have to figure out if they can have a mature relationship. If these two overgrown adolescents can grow from freshmen into real men, college might be the best thing that ever happened to them.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTcwNzAxMDU1M15BMl5BanBnXkFtZTgwNDE2NTU1MTE@._V1_SX300.jpg", rated: "R", runtime: "112 min", actors: "Jonah Hill, Channing Tatum, Peter Stormare, Wyatt Russell", imdb_rating: "7.1"},
  {title: "30 Minutes or Less", year: 2011, checked_out: false, reserved: true, description: "Two fledgling criminals kidnap a pizza delivery guy, strap a bomb to his chest, and inform him that he has mere hours to rob a bank or else...", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTM5NjM0ODY1NF5BMl5BanBnXkFtZTcwMjk5NjI0Ng@@._V1_SX300.jpg", rated: "R", runtime: "83 min", actors: "Jesse Eisenberg, Danny McBride, Aziz Ansari, Nick Swardson", imdb_rating: "6.1"},
  {title: "American Sniper", year: 2014, checked_out: false, reserved: false, description: "Chris Kyle was nothing more than a Texan man who dreamed of becoming a cowboy, but in his thirties he found out that maybe his life needed something different, something where he could express his real talent, something that could help America in its fight against terrorism. So he joined the SEALs in order to become a sniper. After marrying, Kyle and the other members of the team are called for their first tour of Iraq. Kyle's struggle isn't with his missions, but about his relationship with the reality of the war and, once returned at home, how he manages to handle it with his urban life, his wife and kids.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTkxNzI3ODI4Nl5BMl5BanBnXkFtZTgwMjkwMjY4MjE@._V1_SX300.jpg", rated: "R", runtime: "133 min", actors: "Bradley Cooper, Kyle Gallner, Cole Konis, Ben Reed", imdb_rating: "7.3"},
  {title: "Anastasia", year: 1997, checked_out: false, reserved: false, description: "The daughter of the last Russian Tsar, Nicolas II, Anastasia is found by two Russian con men, Dimitri and Vladimir, who seek the reward that her grandmother, the Dowager Empress Marie, promised to the ones who'll find her. But the evil mystic of the Tsar family, Rasputin, still wants the Romanov family to be destroyed forever.", times_rented: nil, img_url: "https://image.tmdb.org/t/p/original/gUv3j1eMDlwKXnCdEnbDozb7JvA.jpg", rated: "G", runtime: "94 min", actors: "Meg Ryan, John Cusack, Kelsey Grammer, Christopher Lloyd", imdb_rating: "7.1"},
  {title: "Angels & Demons", year: 2009, checked_out: false, reserved: false, description: "Following the murder of a physicist, Father Silvano Bentivoglio, a symbolist, Robert Langdon, and a scientist, Vittoria Vetra, are on an adventure involving a secret brotherhood, the Illuminati. Clues lead them all around the Vatican, including the four altars of science, Earth, Air, Fire and Water. An assassin, working for the Illuminati, has captured four cardinals, and murders each, painfully. Robert and Vittoria also are searching for a new very destructive weapon that could kill millions.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMjEzNzM2MjgxMF5BMl5BanBnXkFtZTcwNTQ1MTM0Mg@@._V1_SX300.jpg", rated: "PG-13", runtime: "138 min", actors: "Tom Hanks, Ewan McGregor, Ayelet Zurer, Stellan Skarsgård", imdb_rating: "6.7"},
  {title: "The Animatrix", year: 2003, checked_out: false, reserved: false, description: "Anthology of nine short anime (Japanese animation) films tied in to the 1999 blockbuster \\\"The Matrix\\\" and its sequels. \\\"Final Flight of the Osiris\\\": The crew of the hovercraft Osiris attempt to warn their city of an imminent attack. \\\"The Second Renaissance, Parts 1 & 2\\\": The story behind the war between man and the machines, how mankind scorched the sky, and the creation of the Matrix. \\\"Kid's Story\\\": A teenager is contacted by Neo, and manages to escape the Matrix. \\\"Program\\\": Two warriors battle in a samurai training simulation when one decides to betray his crewmates and re-enter the Matrix. \\\"World Record\\\": A champion sprinter manages to break free of the Matrix by sheer physical effort during a record attempt. \\\"Beyond\\\": A young girl searching for her cat discovers a haunted house caused by a glitch in the system. \\\"A Detective Story\\\": Private investigator Ash tracks a hacker named Trinity through the looking glass. \\\"Matriculated\\\": A group of humans capture a machine scout and insert it into a 'human matrix'.", times_rented: nil, img_url: "https://image.tmdb.org/t/p/w325/1ISkdhJ48PDvETdxjllQ1AswTGv.jpg", rated: "PG-13", runtime: "100 min", actors: "Clayton Watson, Akio Ôtsuka, Pamela Adlon, Hedy Burress", imdb_rating: "7.4"},
  {title: "Annie", year: 1982, checked_out: false, reserved: false, description: "In the depths of the 1930's, Annie is a fiery young orphan girl who must live in a miserable orphanage run by the tyrannical Miss Hannigan. Her seemingly hopeless situation changes dramatically when she is selected to spend a short time at the residence of the wealthy munitions industrialist, Oliver Warbucks. Quickly, she charms the hearts of the household staff and even the seemingly cold-hearted Warbucks cannot help but learn to love this wonderful girl. He decides to help Annie find her long lost parents by offering a reward if they would come to him and prove their identity. However, Miss Hannigan, her evil brother, Rooster, and a female accomplice, plan to impersonate those people to get the reward for themselves which put Annie in great danger.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTczMjgwNTAyNV5BMl5BanBnXkFtZTcwMDU3MzMyMQ@@._V1_SX300.jpg", rated: "PG", runtime: "127 min", actors: "Albert Finney, Carol Burnett, Ann Reinking, Tim Curry", imdb_rating: "6.5"},
  {title: "Ant-Man", year: 2015, checked_out: false, reserved: false, description: "Armed with the astonishing ability to shrink in scale but increase in strength, con-man Scott Lang must embrace his inner-hero and help his mentor, Dr. Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that will save the world.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMjM2NTQ5Mzc2M15BMl5BanBnXkFtZTgwNTcxMDI2NTE@._V1_SX300.jpg", rated: "PG-13", runtime: "117 min", actors: "Paul Rudd, Michael Douglas, Evangeline Lilly, Corey Stoll", imdb_rating: "7.4"},
  {title: "Are You Here", year: 2013, checked_out: false, reserved: false, description: "Ben Baker is a man-child who lives on his friend's couch getting high. His friend, Steve Dallas, is a moderately successful weather reporter who is living a superficial life. When Ben receives word that his father has died, Steve drives him home and they re-connect with Ben's successful and driven sister Terri and hippie step-mother Angela who is the same age as they are. The reading of the will drives Ben to come up with a new purpose in life, but those around him don't prove to be very supportive, and then they all re-examine their own life.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BNjY3NzM2NDg0MV5BMl5BanBnXkFtZTgwOTE2MjU5MTE@._V1_SX300.jpg", rated: "R", runtime: "114 min", actors: "Owen Wilson, Jay Gates, Jason Davis, Melissa Rauch, Amy Poehler", imdb_rating: "5.3"},
  {title: "The Avengers", year: 2012, checked_out: false, reserved: false, description: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTk2NTI1MTU4N15BMl5BanBnXkFtZTcwODg0OTY0Nw@@._V1_SX300.jpg", rated: "PG-13", runtime: "143 min", actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth", imdb_rating: "8.1"},
  {title: "Avengers: Age of Ultron", year: 2015, checked_out: false, reserved: false, description: "Tony Stark creates the Ultron Program to protect the world, but when the peacekeeping program becomes hostile, The Avengers go into action to try and defeat a virtually impossible enemy together. Earth's mightiest heroes must come together once again to protect the world from global extinction", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTM4OGJmNWMtOTM4Ni00NTE3LTg3MDItZmQxYjc4N2JhNmUxXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SX300.jpg", rated: "PG-13", runtime: "141 min", actors: "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans", imdb_rating: "7.5"},
  {title: "Band of Brothers", year: 2001, checked_out: false, reserved: false, description: "The story of Easy Company of the US Army 101st Airborne division and their mission in WWII Europe from Operation Overlord through V-J Day.", times_rented: nil, img_url: "https://image.tmdb.org/t/p/w325/bUrt6oeXd04ImEwQjO9oLjRguaA.jpg", rated: "TV-MA", runtime: "N/A", actors: "Scott Grimes, Damian Lewis, Ron Livingston, Shane Taylor", imdb_rating: "9.5"},
  {title: "Baby Mama", year: 2008, checked_out: false, reserved: false, description: "A successful, single businesswoman who dreams of having a baby discovers she is infertile and hires a working class woman to be her unlikely surrogate.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTYwNTc1Nzk1N15BMl5BanBnXkFtZTcwNjE4OTI2MQ@@._V1_SX300.jpg", rated: "PG-13", runtime: "99 min", actors: "Amy Poehler, Tina Fey, Greg Kinnear, Dax Shepard", imdb_rating: "6.0"},
  {title: "Batman Begins", year: 2005, checked_out: false, reserved: false, description: "When his parents are killed, billionaire playboy Bruce Wayne relocates to Asia where he is mentored by Henri Ducard and Ra's Al Ghul in how to fight evil. When learning about the plan to wipe out evil in Gotham City by Ducard, Bruce prevents this plan from getting any further and heads back to his home. Back in his original surroundings, Bruce adopts the image of a bat to strike fear into the criminals and the corrupt as the icon known as 'Batman'. But it doesn't stay quiet for long.", times_rented: nil, img_url: "https://image.tmdb.org/t/p/w325/xiosOeLfzPbfLfqui41kSWnO0sZ.jpg", rated: "PG-13", runtime: "140 min", actors: "Christian Bale, Michael Caine, Liam Neeson, Katie Holmes", imdb_rating: "8.3"},
  {title: "Battle Los Angeles", year: 2011, checked_out: false, reserved: false, description: "A squadron of U.S. Marines becomes the last line of defense against a global invasion.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMjA2MjQ2MzMwMV5BMl5BanBnXkFtZTcwMjIwODgzNA@@._V1_SX300.jpg", rated: "PG-13", runtime: "116 min", actors: "Aaron Eckhart, Ramon Rodriguez, Will Rothhaar, Cory Hardrict", imdb_rating: "5.8"},
  {title: "Big Hero 6", year: 2014, checked_out: false, reserved: false, description: "The special bond that develops between plus-sized inflatable robot Baymax, and prodigy Hiro Hamada, who team up with a group of friends to form a band of high-tech heroes.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMDliOTIzNmUtOTllOC00NDU3LWFiNjYtMGM0NDc1YTMxNjYxXkEyXkFqcGdeQXVyNTM3NzExMDQ@._V1_SX300.jpg", rated: "PG", runtime: "102 min", actors: "Scott Adsit, Ryan Potter, Daniel Henney, T.J. Miller", imdb_rating: "7.9"},
  {title: "The Big Short", year: 2015, checked_out: false, reserved: false, description: "Three separate but parallel stories of the U.S mortgage housing crisis of 2005 are told. Michael Burry, an eccentric ex-physician turned one-eyed Scion Capital hedge fund manager, has traded traditional office attire for shorts, bare feet and a Supercuts haircut. He believes that the US housing market is built on a bubble that will burst within the next few years. Autonomy within the company allows Burry to do largely as he pleases, so Burry proceeds to bet against the housing market with the banks, who are more than happy to accept his proposal for something that has never happened in American history. The banks believe that Burry is a crackpot and therefore are confident in that they will win the deal. Jared Vennett with Deutschebank gets wind of what Burry is doing and, as an investor believes he too can cash in on Burry's beliefs. An errant telephone call to FrontPoint Partners gets this information into the hands of Mark Baum, an idealist who is fed up with the corruption in the financial industry. Baum and his associates, who work at an arms length under Morgan Stanley, decide to join forces with Vennett despite not totally trusting him. In addition to Burry's information, they further believe that most of the mortgages are overrated by the bond agencies, with the banks collating all the sub-prime mortgages under AAA packages. Charlie Geller and Jamie Shipley, who are minor players in a $30 million start-up garage company called Brownfield, get a hold of Vennett's prospectus on the matter. Wanting in on the action but not having the official clout to play, they decide to call an old \\\"friend\\\", retired investment banker Ben Rickert, to help out. All three of these groups work on the premise that the banks are stupid and don't know what's going on, while for them to win, the general economy has to lose, which means the suffering of the general investor who trusts the financial institutions. That latter aspect may not sit well with Baum. Some of these assumptions may be incorrect and may be far more manipulative than they could have ever imagined, which in turn may throw curves into the process.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BNDc4MThhN2EtZjMzNC00ZDJmLThiZTgtNThlY2UxZWMzNjdkXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg", rated: "R", runtime: "130 min", actors: "Ryan Gosling, Rudy Eisenzopf, Casey Groves, Charlie Talbert", imdb_rating: "7.8"},
  {title: "Blades of Glory", year: 2007, checked_out: false, reserved: false, description: "When rivalry between the world's best men's figure skaters - sex addicted, improvisational Chazz Michael Michaels and germophobic, precise Jimmy MacElroy - breaks into a fight on the awards platform, they're banned from the event for life. Three years later, desire for a gold medal and a careful reading of the rules lead them to compete as skating's first male-male pair. Can they overcome mutual dislike, limited time to prepare, their coach's secret past, and the dirty tricks of their main opponents, the Van Waldenberg siblings? The key to victory or defeat may lie in the attraction of the virginal Jimmy toward Katie, the Van Waldenbergs' little sister.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTY3MDMyMTYxMl5BMl5BanBnXkFtZTcwMjk0NzI0MQ@@._V1_SX300.jpg", rated: "PG-13", runtime: "93 min", actors: "Will Ferrell, Jon Heder, Will Arnett, Amy Poehler", imdb_rating: "6.3"},
  {title: "The Bourne Identity", year: 2002, checked_out: false, reserved: false, description: "Based very loosely on Robert Ludlum's novel, the Bourne Identity is the story of a man whose wounded body is discovered by fishermen who nurse him back to health. He can remember nothing and begins to try to rebuild his memory based on clues such as a Swiss bank account, the number of which is implanted in his hip. He soon realizes that he is being hunted and takes off with Marie on a search to find out who he is - and why he is being hunted.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BNDRmOGQ0ZjktMTQ5Zi00NTZlLTk5MjktOWY4ZjcyOGE5OGRlXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg", rated: "PG-13", runtime: "119 min", actors: "Matt Damon, Franka Potente, Chris Cooper, Clive Owen", imdb_rating: "7.9"},
  {title: "The Bourne Supremacy", year: 2004, checked_out: false, reserved: false, description: "When Jason Bourne is framed for a CIA operation gone awry, he is forced to resume his former life as a trained assassin to survive.", times_rented: nil, img_url: "https://image.tmdb.org/t/p/w325/6a74OaZArLNNDHK9SdiLBUu2JYj.jpg", rated: "PG-13", runtime: "108 min", actors: "Matt Damon, Franka Potente, Brian Cox, Julia Stiles", imdb_rating: "7.8"},
  {title: "The Bourne Ultimatum", year: 2007, checked_out: false, reserved: false, description: "Jason Bourne dodges a ruthless CIA official and his agents from a new assassination program while searching for the origins of his life as a trained killer.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTgzNjMwOTM3N15BMl5BanBnXkFtZTcwMzA5MDY0MQ@@._V1_SX300.jpg", rated: "PG-13", runtime: "115 min", actors: "Matt Damon, Julia Stiles, David Strathairn, Scott Glenn", imdb_rating: "8.1"},
  {title: "The Bourne Legacy", year: 2015, checked_out: false, reserved: false, description: "An expansion of the universe from Robert Ludlum's novels, centered on a new hero whose stakes have been triggered by the events of the previous three films.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTc4Njk3MDM1Nl5BMl5BanBnXkFtZTcwODgyOTMxOA@@._V1_SX300.jpg", rated: "PG-13", runtime: "135 min", actors: "Jeremy Renner, Scott Glenn, Stacy Keach, Edward Norton", imdb_rating: "6.7"},
  {title: "Brooklyn", year: 2015, checked_out: false, reserved: false, description: "An Irish immigrant lands in 1950s Brooklyn, where she quickly falls into a romance with a local. When her past catches up with her, however, she must choose between two countries and the lives that exist within.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMzE4MDk5NzEyOV5BMl5BanBnXkFtZTgwNDM4NDA3NjE@._V1_SX300.jpg", rated: "PG-13", runtime: "111 min", actors: "Saoirse Ronan, Hugh Gormley, Brid Brennan, Maeve McGrath", imdb_rating: "7.5"},
  {title: "The Campaign", year: 2012, checked_out: false, reserved: false, description: "When Cam Brady (D-NC), a four-term Congressman, becomes a liability, the Motch brothers (think Koch brothers) recruit Marty Huggins, the son of a Republican heavy hitter, to run against him and be their vehicle to establish factories in the district that will import cheap Chinese labor. Trouble is, Marty is a lightweight, so his makeover falls to consultant Tim Wattley. The race tightens as Cam constantly shoots himself in the foot, while the prospect of winning also changes Marty and his family's dynamics. Meanwhile, Cam plays dirty, and Marty cottons on to the Moches' grand plan. What options do the rich have to get their way?", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTY0NjI3MzM2Nl5BMl5BanBnXkFtZTcwNDgxNjA5Nw@@._V1_SX300.jpg", rated: "R", runtime: "85 min", actors: "Will Ferrell, Zach Galifianakis, Jason Sudeikis, Dylan McDermott", imdb_rating: "6.2"},
  {title: "Captain America: The First Avenger", year: 2011, checked_out: false, reserved: false, description: "Steve Rogers, a rejected military soldier transforms into Captain America after taking a dose of a \"Super-Soldier serum\". But being Captain America comes at a price as he attempts to take down a war monger and a terrorist organization.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTYzOTc2NzU3N15BMl5BanBnXkFtZTcwNjY3MDE3NQ@@._V1_SX300.jpg", rated: "PG-13", runtime: "124 min", actors: "Chris Evans, Hayley Atwell, Sebastian Stan, Tommy Lee Jones", imdb_rating: "6.9"},
  {title: "The Brothers Grimm", year: 2005, checked_out: false, reserved: false, description: "Folklore collectors and con artists, Jake and Will Grimm, travel from village to village pretending to protect townsfolk from enchanted creatures and performing exorcisms. They are put to the test, however, when they encounter a real magical curse in a haunted forest with real magical beings, requiring genuine courage.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTk0OTY1NTc2M15BMl5BanBnXkFtZTcwMDkyNzEzMQ@@._V1_SX300.jpg", rated: "PG-13", runtime: "118 min", actors: "Matt Damon, Heath Ledger, Monica Bellucci", imdb_rating: "5.9"},
  {title: "Captain America: The Winter Soldier", year: 2014, checked_out: false, reserved: false, description: "For Steve Rogers, awakening after decades of suspended animation involves more than catching up on pop culture; it also means that this old school idealist must face a world of subtler threats and difficult moral complexities. That becomes clear when Director Nick Fury is killed by the mysterious assassin, the Winter Soldier, but not before warning Rogers that SHIELD has been subverted by its enemies. When Rogers acts on Fury's warning to trust no one there, he is branded as a traitor by the organization. Now a fugitive, Captain America must get to the bottom of this deadly mystery with the help of the Black Widow and his new friend, The Falcon. However, the battle will be costly for the Sentinel of Liberty, with Rogers finding enemies where he least expects them while learning that the Winter Soldier looks disturbingly familiar.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMzA2NDkwODAwM15BMl5BanBnXkFtZTgwODk5MTgzMTE@._V1_SX300.jpg", rated: "PG-13", runtime: "136 min", actors: "Chris Evans, Samuel L. Jackson, Scarlett Johansson, Robert Redford", imdb_rating: "7.8"},
  {title: "Casino Royale", year: 2006, checked_out: false, reserved: false, description: "Armed with a licence to kill, Secret Agent James Bond sets out on his first mission as 007 and must defeat a weapons dealer in a high stakes game of poker at Casino Royale, but things are not what they seem.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTM5MjI4NDExNF5BMl5BanBnXkFtZTcwMDM1MjMzMQ@@._V1_SX300.jpg", rated: "PG-13", runtime: "144 min", actors: "Daniel Craig, Eva Green, Mads Mikkelsen, Judi Dench", imdb_rating: "8.0"},
  {title: "Chappie", year: 2015, checked_out: false, reserved: false, description: "In the near future, crime is patrolled by a mechanized police force. When one police droid, Chappie, is stolen and given new programming, he becomes the first robot with the ability to think and feel for himself.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTUyNTI4NTIwNl5BMl5BanBnXkFtZTgwMjQ4MTI0NDE@._V1_SX300.jpg", rated: "R", runtime: "120 min", actors: " Sharlto Copley, Dev Patel, Hugh Jackman", imdb_rating: "6.9"},
  {title: "Constantine", year: 2005, checked_out: false, reserved: false, description: "John Constantine is approached by Det. Angela Dodson who needs his help to prove that her twin sister Isabel's death was not a suicide. The dead woman was a devout Catholic and Angela refuses to accept she would have taken her own life. She's asked Constantine for help because he has a reputation for dealing with the mystical. In fact, he is a demon hunter whose sole purpose on Earth is to send demons back to the nether regions. John himself has been to Hell and knows that he is destined to return there on his death - but hopes his good deeds may find him a place in Heaven. As he looks into Isabel's death, he realizes demons are trying to break through to the human world, and his battles lead him into a direct conflict with Satan.", times_rented: nil, img_url: "https://image.tmdb.org/t/p/original/qYTerimWp1t1zSEKknn9mByhwbX.jpg", rated: "R", runtime: "121 min", actors: "Keanu Reeves, Rachel Weisz, Shia LaBeouf, Djimon Hounsou", imdb_rating: "6.9"},
  {title: "Couples Retreat", year: 2009, checked_out: false, reserved: false, description: "Dave and Ronnie, Jason and Cynthia, and Joey and Lucy are close. The group used to include Shane and Jennifer, but they divorced and she's gone. Jason and Cynthia announce that their marriage is in trouble, and they beg their friends (and Shane's young girlfriend) to join them on a couples' retreat, at the package rate, on a tropical island. The others reluctantly agree, planning to play while Jason and Cynthia work on their marriage with an island psychologist. To everyone's surprise, the package is inflexible: each couple must participate in the couples' exercises. Soon fault lines appear in all four relationships. What's in store for each couple?", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTQxMjI1Nzc0M15BMl5BanBnXkFtZTcwMTc0Mzg2Mg@@._V1_SX300.jpg", rated: "PG-13", runtime: "113 min", actors: "Vince Vaughn, Jason Bateman, Faizon Love, Jon Favreau", imdb_rating: "5.5"},
  {title: "Crazy, Stupid, Love.", year: 2011, checked_out: false, reserved: false, description: "A middle-aged husband's life changes dramatically when his wife asks him for a divorce. He seeks to rediscover his manhood with the help of a newfound friend, Jacob, learning to pick up girls at bars.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTg2MjkwMTM0NF5BMl5BanBnXkFtZTcwMzc4NDg2NQ@@._V1_SX300.jpg", rated: "PG-13", runtime: "118 min", actors: "Steve Carell, Ryan Gosling, Julianne Moore, Emma Stone", imdb_rating: "7.4"},
  {title: "Dan in Real Life", year: 2007, checked_out: false, reserved: false, description: "A widower finds out the woman he fell in love with is his brother's girlfriend.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMjA2Nzc1NzQ1OV5BMl5BanBnXkFtZTcwOTE0MDE1MQ@@._V1_SX300.jpg", rated: "PG-13", runtime: "98 min", actors: "Steve Carell, Juliette Binoche, Dane Cook, Alison Pill", imdb_rating: "6.8"},
  {title: "2 Fast 2 Furious", year: 2003, checked_out: false, reserved: false, description: "EX LAPD cop Brian O'Conner (Paul Walker) teams up with his ex-con friend Roman Pearce (Tyrese Gibson) and works with undercover U.S. Customs Service agent Monica Fuentes (Eva Mendes) to bring Miami-based drug lord Carter Verone (Cole Hauser) down.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTIyMDUwMDc4OF5BMl5BanBnXkFtZTYwNTY2Nzk5._V1_SX300.jpg", rated: "PG-13", runtime: "107 min", actors: "Paul Walker, Tyrese Gibson, Eva Mendes, Cole Hauser", imdb_rating: "5.9"},
  {title: "Cinderella", year: 2015, checked_out: false, reserved: true, description: "A girl named Ella (Cinderella) has the purest heart living in a cruel world filled with evil stepsisters and an evil stepmother out to ruin Ella's life. Ella comes one with her pure heart when she meets the prince and dances her way to a better life with glass shoes, and a little help from her fairy godmother, of course.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMjMxODYyODEzN15BMl5BanBnXkFtZTgwMDk4OTU0MzE@._V1_SX300.jpg", rated: "PG", runtime: "105 min", actors: "Cate Blanchett, Lily James, Richard Madden, Helena Bonham Carter", imdb_rating: "7.0"},
  {title: "Daredevil", year: 2003, checked_out: false, reserved: true, description: "Fate deals young orphan Matt Murdock a strange hand when he is doused with hazardous waste. The accident leaves Matt blind but also gives him a heightened \"radar sense\" that allows him to \"see\" far better than any man. Years later Murdock has grown into a man and becomes a respected criminal attorney. But after he's done his \"day job\" Matt takes on a secret identity as \"The Man Without Fear,\" Daredevil, the masked avenger that patrols the neighborhood of Hell's Kitchen and New York City to combat the injustice that he cannot tackle in the courtroom.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMzU3MDUxNjYwNl5BMl5BanBnXkFtZTYwNzQ3Nzc2._V1_SX300.jpg", rated: "PG-13", runtime: "103 min", actors: "Ben Affleck, Jennifer Garner, Colin Farrell, Michael Clarke Duncan", imdb_rating: "5.3"},
  {title: "The Dark Knight", year: 2008, checked_out: false, reserved: false, description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg", rated: "PG-13", runtime: "152 min", actors: "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine", imdb_rating: "9.0"},
  {title: "Behind Enemy Lines", year: 2001, checked_out: false, reserved: false, description: "Fighter navigator Chris Burnett wants out: he was looking for something more than the boring recon missions he's been flying. He finds himself flying the lone Christmas day mission over war-torn Bosnia. But when he talks pilot Stackhouse into flying slightly off-course to check out an interesting target, the two get shot down. Burnett is soon alone, trying to outrun a pursuing army, while commanding officer Reigert finds his rescue operation hamstrung by politics, forcing Burnett to run far out of his way.", times_rented: nil, img_url: "http://ia.media-imdb.com/images/M/MV5BMTQ0MzMwMDI4M15BMl5BanBnXkFtZTcwMTAxMDMyMQ@@._V1_SX300.jpg", rated: "PG-13", runtime: "106 min", actors: "Owen Wilson, Gene Hackman, Gabriel Macht, Charles Malik Whitfield", imdb_rating: "6.4"}
])
User.create!([
  {email: "fake@gmail.com", encrypted_password: "$2a$11$WUC0LfvbsZYSxmzIw5te9eNyLTMxZPmJEBc/LO6Wxf81Z0/0PzxsK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2016-09-27 23:35:13", last_sign_in_at: "2016-09-26 06:31:14", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", username: "John Smith", provider: nil, uid: nil},
  {email: "s3nbonzakura78@gmail.com", encrypted_password: "$2a$11$fUk/drq.H58Y06mo0v9Am.OV.smCiEjzvePC10GgE5ws5jVa230Je", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 24, current_sign_in_at: "2016-10-29 02:43:16", last_sign_in_at: "2016-10-26 08:13:35", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", username: "Josh Avina", provider: "facebook", uid: "10154007225642428"},
  {email: "testedit@gmail.com", encrypted_password: "$2a$11$YkQL.ZePhP35i7pELrwFx.Uss.hyMuIvDChU9f2j4B7akepJtAHMO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-10-30 00:37:53", last_sign_in_at: "2016-10-27 03:44:09", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", username: "John Smith", provider: nil, uid: nil}
])
Genre.create!([
  {name: "Tv Shows"},
  {name: "Action"},
  {name: "Anime"},
  {name: "Children & Family"},
  {name: "Classics"},
  {name: "Comedies"},
  {name: "Cult Movies"},
  {name: "Documentaries"},
  {name: "Dramas"},
  {name: "Faith & Spirituality"},
  {name: "Horror"},
  {name: "Independent"},
  {name: "International"},
  {name: "Musicals"},
  {name: "Romance"},
  {name: "Sci-Fi & Fantasy"},
  {name: "Sports Movies"},
  {name: "Thrillers"},
  {name: "Crime"},
  {name: "Adventure"},
  {name: "Mystery"},
  {name: "History"}
])
Categorization.create!([
  {movie_id: 2, genre_id: 5},
  {movie_id: 2, genre_id: 6},
  {movie_id: 3, genre_id: 1},
  {movie_id: 3, genre_id: 3},
  {movie_id: 4, genre_id: 4},
  {movie_id: 5, genre_id: 2},
  {movie_id: 5, genre_id: 5},
  {movie_id: 5, genre_id: 7},
  {movie_id: 6, genre_id: 2},
  {movie_id: 6, genre_id: 9},
  {movie_id: 6, genre_id: 18},
  {movie_id: 7, genre_id: 2},
  {movie_id: 7, genre_id: 18},
  {movie_id: 7, genre_id: 19},
  {movie_id: 8, genre_id: 2},
  {movie_id: 8, genre_id: 6},
  {movie_id: 8, genre_id: 19},
  {movie_id: 9, genre_id: 2},
  {movie_id: 9, genre_id: 9},
  {movie_id: 9, genre_id: 16},
  {movie_id: 10, genre_id: 2},
  {movie_id: 10, genre_id: 9},
  {movie_id: 10, genre_id: 16},
  {movie_id: 11, genre_id: 2},
  {movie_id: 11, genre_id: 6},
  {movie_id: 11, genre_id: 19},
  {movie_id: 12, genre_id: 2},
  {movie_id: 12, genre_id: 9},
  {movie_id: 12, genre_id: 19},
  {movie_id: 13, genre_id: 2},
  {movie_id: 13, genre_id: 9},
  {movie_id: 13, genre_id: 20},
  {movie_id: 14, genre_id: 6},
  {movie_id: 14, genre_id: 9},
  {movie_id: 14, genre_id: 15},
  {movie_id: 15, genre_id: 2},
  {movie_id: 15, genre_id: 20},
  {movie_id: 16, genre_id: 6},
  {movie_id: 16, genre_id: 9},
  {movie_id: 16, genre_id: 15},
  {movie_id: 17, genre_id: 2},
  {movie_id: 17, genre_id: 16},
  {movie_id: 17, genre_id: 20},
  {movie_id: 18, genre_id: 2},
  {movie_id: 18, genre_id: 16},
  {movie_id: 18, genre_id: 20},
  {movie_id: 19, genre_id: 2},
  {movie_id: 19, genre_id: 9},
  {movie_id: 20, genre_id: 2},
  {movie_id: 20, genre_id: 4},
  {movie_id: 20, genre_id: 20},
  {movie_id: 21, genre_id: 18},
  {movie_id: 21, genre_id: 21},
  {movie_id: 22, genre_id: 2},
  {movie_id: 22, genre_id: 3},
  {movie_id: 22, genre_id: 20},
  {movie_id: 23, genre_id: 4},
  {movie_id: 23, genre_id: 6},
  {movie_id: 23, genre_id: 9},
  {movie_id: 24, genre_id: 2},
  {movie_id: 24, genre_id: 6},
  {movie_id: 24, genre_id: 20},
  {movie_id: 24, genre_id: 16},
  {movie_id: 25, genre_id: 6},
  {movie_id: 25, genre_id: 9},
  {movie_id: 26, genre_id: 2},
  {movie_id: 26, genre_id: 16},
  {movie_id: 26, genre_id: 18},
  {movie_id: 27, genre_id: 2},
  {movie_id: 27, genre_id: 16},
  {movie_id: 27, genre_id: 20},
  {movie_id: 28, genre_id: 6},
  {movie_id: 28, genre_id: 15},
  {movie_id: 29, genre_id: 1},
  {movie_id: 29, genre_id: 2},
  {movie_id: 29, genre_id: 9},
  {movie_id: 29, genre_id: 22},
  {movie_id: 30, genre_id: 2},
  {movie_id: 30, genre_id: 16},
  {movie_id: 30, genre_id: 20},
  {movie_id: 31, genre_id: 2},
  {movie_id: 31, genre_id: 16},
  {movie_id: 32, genre_id: 2},
  {movie_id: 32, genre_id: 9},
  {movie_id: 33, genre_id: 2},
  {movie_id: 33, genre_id: 4},
  {movie_id: 33, genre_id: 20},
  {movie_id: 34, genre_id: 6},
  {movie_id: 34, genre_id: 9},
  {movie_id: 35, genre_id: 6},
  {movie_id: 35, genre_id: 17},
  {movie_id: 36, genre_id: 2},
  {movie_id: 36, genre_id: 18},
  {movie_id: 36, genre_id: 21},
  {movie_id: 37, genre_id: 2},
  {movie_id: 37, genre_id: 18},
  {movie_id: 37, genre_id: 21},
  {movie_id: 38, genre_id: 2},
  {movie_id: 38, genre_id: 18},
  {movie_id: 38, genre_id: 21},
  {movie_id: 39, genre_id: 2},
  {movie_id: 39, genre_id: 9},
  {movie_id: 39, genre_id: 20},
  {movie_id: 40, genre_id: 9},
  {movie_id: 40, genre_id: 15},
  {movie_id: 41, genre_id: 2},
  {movie_id: 41, genre_id: 6},
  {movie_id: 41, genre_id: 20},
  {movie_id: 42, genre_id: 6},
  {movie_id: 43, genre_id: 2},
  {movie_id: 43, genre_id: 16},
  {movie_id: 43, genre_id: 20},
  {movie_id: 44, genre_id: 2},
  {movie_id: 44, genre_id: 16},
  {movie_id: 44, genre_id: 20},
  {movie_id: 45, genre_id: 2},
  {movie_id: 45, genre_id: 18},
  {movie_id: 45, genre_id: 20},
  {movie_id: 46, genre_id: 2},
  {movie_id: 46, genre_id: 9},
  {movie_id: 46, genre_id: 19},
  {movie_id: 47, genre_id: 4},
  {movie_id: 47, genre_id: 9},
  {movie_id: 47, genre_id: 16},
  {movie_id: 48, genre_id: 9},
  {movie_id: 48, genre_id: 11},
  {movie_id: 48, genre_id: 16},
  {movie_id: 49, genre_id: 6},
  {movie_id: 50, genre_id: 6},
  {movie_id: 50, genre_id: 9},
  {movie_id: 50, genre_id: 15},
  {movie_id: 51, genre_id: 6},
  {movie_id: 51, genre_id: 9},
  {movie_id: 51, genre_id: 15},
  {movie_id: 52, genre_id: 2},
  {movie_id: 52, genre_id: 9},
  {movie_id: 52, genre_id: 19},
  {movie_id: 53, genre_id: 2},
  {movie_id: 53, genre_id: 9},
  {movie_id: 53, genre_id: 16},
  {movie_id: 53, genre_id: 19}
])
